### ISSUE TITLE
【bug】当保持长连接时，请求不会切换随机ip

### ISSUE THREAD

**Issue by zhuxindong** [zu1k/http-proxy-ipv6-pool#13]
【bug】当客户端保持长连接时，每次请求不会切换随机ip

**Comment by zu1k** [comment]
提供的 http 代理只会对每一个 connect 请求进行处理，如果http proxy客户端对同一host保持 tcp 长链接，则无法切换 ip。如果想要实现对每一个 http 请求都切换 ip，则需要对 http 请求进行 MITM。

不过本程序不仅要支持 http 协议，还要支持任何使用 tcp 的其他协议，所以暂时没有进一步优化的打算

**Comment by zhuxindong** [comment]
除了mitm，是否还有别的方式实现。或者请教下mitm的实现思路

**Comment by zu1k** [comment]
> 除了mitm，是否还有别的方式实现

其实改一下客户端的行为让它不要长连接事最方便的，你都要换ip了长连接有啥用


> 请教下mitm的实现思路

可以读一下这里的代码 https://github.com/zu1k/Good-MITM

**Comment by zhuxindong** [comment]
现在大部分客户端默认都是开启长连接的。非常感谢。
