### ISSUE TITLE
Unable to do apt update or apt install

### ISSUE THREAD

**Issue by oliking800** [zu1k/http-proxy-ipv6-pool#3]
After i did the ip route and stuff. i can no longer do apt update or apt install

Do you want to continue? [Y/n] y
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-122.138
Err:1 http://security.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-122.138
  404  Not Found [IP: 2001:67c:1562::15 80]
Unable to correct missing packages.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-122.138_amd64.deb  404  Not Found [IP: 2001:67c:1562::15 80]
E: Aborting install.

anyway to fix this?

**Comment by zu1k** [comment]
http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-122.138_amd64.deb is really 404.

Maybe not caused by this.

**Comment by oliking800** [comment]
nah it is fixed now. i just had to reinstall ndppd and restart it

**Comment by zu1k** [comment]
> http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.4.0-122.138_amd64.deb is really 404.

Why do you get an invalid url, have you updated the indexes?
